### ISSUE TITLE
systematic check on the compatibility between molecular symmetry and Wyckoff site symmetry

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/crystallography#11]
Let's use CH4, H2O, NH3 as examples to do the following,
1, For each molecule, systematically scan all space groups
2,For each space group, systematically scan all Wyckoff sites, if their site symmetry is compatible with the molecular internal symmetry, output all possible orientations.

**Comment by qzhu2017** [comment]
The first code in done in c6dfb7c. 
@scottfredericks, please have a look and check if the results are reasonable to you.

After passing these tests, we can proceed to work on the generation of molecular crystals!

**Comment by scottfredericks** [comment]
@qzhu2017 
Looking through the results, I noticed that the program does not detect any positions for spacegroups 1 and 2; I am not sure why this is, but I think it has to do with the orientation check. Additionally, CS2 has a math domain error for acos in spacegroup 90. I should be able to change the "angle" function to prevent this.

**Comment by scottfredericks** [comment]
@qzhu2017 
Regarding the first issue: I did not realize the script does not check the general Wyckoff postition for each space group; this makes sense, so there's no issue.
For the second issue: I changed matrix.angle() to check for dot products of 1 or -1; this should eliminate the math domain error. The program is currently running past the point where it failed last time.
Looking through the results again, I noticed that some of the Wyckoff positions have listed site symmetry of "1", and that there can be 1 or 2 orientations for these positions. I think this is just a bug in the site symmetry printing function; I will work on fixing it.

**Comment by scottfredericks** [comment]
@qzhu2017 
The results now look correct for all space groups for H2O, CS2, and CH4. I still need to check through the Wyckoff positions which did not output any allowed orientations, but for all other positions, I believe the number of orientations is correct. I will try to check the unallowed Wyckoff positions, as well as NH3 and C60, by tomorrow, though C60 might take some time to develop an intuition for.

For the site symmetry printing function, the output is now correct, though my notation is slightly different from the Bilbao server's. Specifically, for spacegroups 75-230, I always insert a space between the primary, secondary, and tertiary portions of the symbol. The symbols can be read as follows:
*For spacegroups 1-74, the 1st, 2nd, and 3rd positions in the symbol represent the x, y, and z axes respectively.
*For 75-194, the first position is the z axis; the second position is the x and y axes; and the 3rd position is for face diagonals, or for any other axis which can be found in trigonal/hexagonal spacegroups.
*For 195-230, the first position is the x,y, and z axes; the second position is for body diagonals, and the 3rd position is for face diagonals.

Note: For groups 75-230, equivalent axes are condensed into a single character. Also, two axes having the same character does not necessarily mean they are symmetrically equivalent. Thus, we have symbols like "2 mm ."

The algorithm used in orientation_in_wyckoff_position has slightly changed:
The program first finds a constraint axis within the Wyckoff point group. Then, corresponding axes in the molecular point group are found. But now, we also consider axes which are pointing in the opposite direction to the Wyckoff axes. 
Next, the program eliminates redundancy for the first constraint by seeing if any two found molecular axes are symmetrically equivalent. Two axes are equivalent if there exists a symmetry operation (in the molecular point group) which maps one axis onto the other. It turns out that comparing moments of inertia is an insufficient test in some cases.
Next, we find a second constraint within the Wyckoff position, then we find corresponding molecular constraints. Again, we also consider axes pointing in the opposite direction.
Previously, we would then eliminate redundancy for the second constraint. But, for this we actually need the orientations matrices, and not just the axes. So, at this point we generate orientations for each pair of constraints. This is accomplished by rotating the first molecular constraint onto the first Wyckoff constraint, then rotating the (transformed) second molecular constraint onto the second Wyckoff constraint, about the axis of the first constraint axis.
We then eliminate redundancy among the orientations by checking if they are symmetrically equivalent. This occurs if the operation mapping one orientation onto the other (in the unaltered reference frame) is a valid symmetry operation for the molecule.
Finally, we check each of the generated orientations directly. If all Wyckoff symmetry operations are valid for the molecule (in the new reference frame), the orientation is valid.

The program is slightly slower because of the changes, but as far as I can tell the results are accurate.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have now tested the function for H2O, CS2, CH4, C60, and NH3. For all Wyckoff positions in all spacegroups, the program now outputs the correct results. If there are any other molecules which you would like to test, please let me know.

Also, I have added functionality for checking chirality, and whether or not the Wcyoff position breaks chirality. By default, the function will return False (and a warning) if a chiral molecule is placed into a spacegroup with rotoinversion or inversion symmetry operations. This can be turned off by setting allow_inversion to True.

**Comment by qzhu2017** [comment]
@scottfredericks Thank you. I think they are all good! I like the option of checking chirality. You have done a wonderful job. I will close the issue soon after I did some checks. You can proceed to work on the random generation of molecular crystals.

**Comment by qzhu2017** [comment]
Seems good.
