### ISSUE TITLE
[bug]structure generation failed

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/crystallography#13]
Sometimes, the program will fail without outputting anything useful.
```
qiangzhu@u-10-240-0-27:~/Desktop/github/crystallography$ python molecular_crystal.py -n 4 -s 61
/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/pymatgen/io/cif.py:44: UserWarning: Please install optional dependency pybtex if youwant to extract references from CIF files.
  warnings.warn("Please install optional dependency pybtex if you"
Error: the stoichiometry is incompatible with the wyckoff sites choice
something is wrong
Traceback (most recent call last):
  File "molecular_crystal.py", line 591, in <module>
    print(len(rand_crystal.coordinates))
AttributeError: 'molecular_crystal' object has no attribute 'coordinates'
```

**Comment by scottfredericks** [comment]
@qzhu2017 
In this case, for spacegroup 61, Wyckoff positions 4b and 4a both require inversional symmetry. Water does not have this symmetry; thus, you cannot generate a crystal with 4 water molecules.

I removed a line which tries to print the structure after it fails to generate. Instead, the script just stops.

In order to generate a crystal with 8 water molecules in spacegroup 61 in a reasonable time, it looks like we still need to increase the volume factor. I will work on adding the inter-atomic distance check; this should let us decrease the inter-molecular distance tolerance, then verify the inter-atomic distances afterward.
